# Generated by Django 3.2.7 on 2021-10-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='')),
                ('slug', models.CharField(default='', max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('value', models.IntegerField(default=0)),
                ('img_avata', models.ImageField(null=True, upload_to='')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
