# Generated by Django 3.2.7 on 2021-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211028_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
