# Generated by Django 3.2.7 on 2021-10-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='name_product',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
