# Generated by Django 3.2.7 on 2021-10-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='slug',
        ),
    ]
