# Generated by Django 3.2.7 on 2021-10-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211028_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ship_active',
            new_name='shipped',
        ),
    ]
