# Generated by Django 3.2.7 on 2021-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_ship_active_order_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_type',
            name='active',
        ),
    ]
